# Cloud Build configuration for Colorado Consent Management Backend
# Builds and deploys to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consent-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/consent-backend:latest'
      - '.'
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consent-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/consent-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'consent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/consent-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,FLASK_ENV=production,USE_MOCK_EMAIL=true,USE_MOCK_SMS=true'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/consent-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/consent-backend:latest'

# Build timeout
timeout: 1200s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
